[package]
name = "libsrtp_rs"
version = "0.1.0"
authors = ["Richard Barnes <rlb@ipv.sx>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[profile.test]
opt-level = 0
debug = true

[features]
cffi = ["libc", "cstr", "cpu-time", "rand"]
default = ["cffi"]

[dev-dependencies]
hex = "0.4.3"
rand = "0.8.3"

[dependencies]
libc = { version = "0.2.93", optional = true }     # Only until we can get rid of src/c/alloc.rs
cstr = { version = "0.2.8", optional = true }      # For C string constants
cpu-time = { version = "1.0.0", optional = true }  # For cipher performance testing in C interface
rand = { version = "0.8.3", optional = true }      # For rand_for_tests functions
num_enum = "0.5.1"         # For enum conversion to numeric values
packed_struct = "0.5"      # For RTP header parsing
constant_time_eq = "0.1.5" # For auth tag checking
hex-literal = "0.3.3"      # For test vector literals
sha-1 = "0.9.6"            # Default, pure-Rust crypto
hmac = "0.11.0"            # Default, pure-Rust crypto
aes = "0.7.4"              # Default, pure-Rust crypto
cipher = "0.3.0"           # Default, pure-Rust crypto
ctr = "0.7.0"              # Default, pure-Rust crypto
aes-gcm = { version = "0.9.2", features = ["aes"] } # Default, pure-Rust crypto
