[package]
name = "libsrtp_rs"
version = "0.1.0"
authors = ["Richard Barnes <rlb@ipv.sx>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[profile.test]
opt-level = 0
debug = true

[dev-dependencies]
hex = "0.4.3"
